# This workflow will install packages, test, build and upload to svn repo

name: Build, Test, Tag, Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install php dependencies
      uses: php-actions/composer@v2
      with:
        dev: no
    - name: Install npm packages and build
      run: |
        npm install
        npm run build
    
  deploy-svn:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: create git tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wordpress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: eko-video
