# This workflow will install packages, test, build and upload to svn repo

name: Build, Test, Tag, Deploy

on:
  push:
    tags:
    - "*"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install php dependencies
      uses: php-actions/composer@v2
      with:
        dev: no
    - name: Install npm packages and build
      run: |
        npm install
        npm run build
    
    - name: Wordpress plugin deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: eko-video

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: eko-video